# Generated by Django 5.2.6 on 2025-09-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "country",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Город"
                    ),
                ),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                (
                    "building_number",
                    models.CharField(max_length=50, verbose_name="Номер дома"),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Строение"
                    ),
                ),
                (
                    "block",
                    models.CharField(blank=True, max_length=50, verbose_name="Корпус"),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
