# Generated by Django 5.2.6 on 2025-09-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("distributor", "Distributor"),
                            ("retailer", "Retailer"),
                            ("individual", "Individual entrepreneur"),
                            ("other", "Other"),
                        ],
                        default="retailer",
                        max_length=30,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=64, verbose_name="ИНН/VAT"),
                ),
                ("contact_person_name", models.CharField(blank=True, max_length=200)),
                ("contact_person_phone", models.CharField(blank=True, max_length=50)),
                ("contact_person_email", models.EmailField(blank=True, max_length=254)),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                (
                    "contract_file",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contacts.contactinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнёр",
                "verbose_name_plural": "Партнёры",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=200)),
                ("bic", models.CharField(blank=True, max_length=20)),
                ("account_number", models.CharField(max_length=64)),
                ("iban", models.CharField(blank=True, max_length=64)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Банковский счёт",
                "verbose_name_plural": "Банковские счета",
            },
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["name"], name="partners_pa_name_057e86_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["partner_type"], name="partners_pa_partner_601eea_idx"
            ),
        ),
    ]
